### ISSUE TITLE
I cannot install the newest version of the mod, the Skyrim versions are greyed out on the FOMOD

### ISSUE THREAD

**Issue by ZukonoMeiyo** [DaymareOn/hdtSMP64#123]
Hello everyone, 

As the title of that post suggest, I was recently unable to complete the installation of the newest version of Faster HDT-SMP, as the options of Skyrim versions to choose were all greyed out and unclickable on the FOMOD of the mod.
I've normally done all of the required downloads for the mod to work, as well as updating SKSE and Skyrim (as I received an error message that prevented me to proceed the launching process), so that is why I'm writing this post on the GitHub page of the mod.
Thank you again for your understanding, the time you will take on that post and the help that you may provide.
Respectfully,

ZukonoMeiyo

**Comment by dutchblizzard** [comment]
yup gotta wait for the update, what this time around seems to take away useally fsmp updates around the same time as cbpc does update but that one updated like 2 weeks ago. so dunno whats up now

**Comment by ZukonoMeiyo** [comment]
Thank you dutchblizzard for answering my inquiry.
Have a nice rest of your day and a peaceful week !
Respectfully,

ZukonoMeiyo

**Comment by DaymareOn** [comment]
Should be solved with FSMP >= 2.3.1.

**Comment by CMT493** [comment]
This is still a problem with MO2. All supported game version options are NOT selectable in the FOMOD.
The other options AVX etc. can be selected, so basically the mod cannot be installed. This has been the case for a long time with the latest version 2.5.1, and 2.5.0, 2.4.0 and others. The last version where the FOMOD works in my experience is 1.50.9-rc1.
